### ISSUE TITLE
Node's Indexer does not resume indexing after stoping the node

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean-node#740]
**Describe the bug**
Node's Indexer does not resume indexing after stoping the node (with Ctrl + C or Cmd + C). The expected behaviour is to resume the last indexed block, not starting from deployer block. The issue is fixed if the startBlock is specified within RPCS env var, but it is not user intuitive/friendly to keep updating startBlock.

**To Reproduce**
1. Run Ocean Node on local with npm run start
2. Wait the node to sync
3. Stop the node
4. Restart node

**Expected behavior**
The expected behaviour is to resume the last indexed block, not starting from deployer block.

**Logs**
[ocean-node-op-sepolia-indexer.txt](https://github.com/user-attachments/files/17556839/ocean-node-op-sepolia-indexer.txt)

**Comment by md00ux** [comment]
- **ocean-node** container was started using docker compose 
- database type => typesense
```yaml
DB_TYPE: 'typesense'
DB_URL: "http://typesense:8108/?apiKey=xyz"
....
typesense:
    image: typesense/typesense:26.0
    container_name: typesense
    ports:
      - "8108:8108"
    networks:
      - backend
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=xyz'
```
